FROM lukemathwalker/cargo-chef:latest-rust-alpine3.24 AS chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .

RUN cargo build --release


{% set runtime_base_image = "dhi.io/static:20251003-alpine3.23" if docker_hardened_images else "gcr.io/distroless/static-debian13" -%}
FROM {{ runtime_base_image }} AS runtime
COPY --from=builder /app/target/release/{{project_name}} /{{project_name}}

{% if backend == 'spring-rs' -%}
COPY --from=builder /app/config config
{% endif -%}

EXPOSE 8080

ENTRYPOINT ["/{{project_name}}"]